"""
Yep.
"""
language_list = [
    '1C',
    'ABNF',
    'Access',
    'Ada',
    'ARM assembler',
    'AVR assembler',
    'ActionScript',
    'Apache',
    'AppleScript',
    'AsciiDoc',
    'AspectJ',
    'AutoHotkey',
    'AutoIt',
    'Awk',
    'Axapta',
    'Bash',
    'Basic',
    'BNF',
    'Brainfuck',
    'C#',
    'C++',
    'C/AL',
    'Cache',
    'CMake',
    'Coq',
    'CSP',
    'CSS',
    'Cap’n Proto',
    'Clojure',
    'CoffeeScript',
    'Crmsh',
    'Crystal',
    'D',
    'DNS Zone file',
    'DOS',
    'Dart',
    'Delphi',
    'Diff',
    'Django',
    'Dockerfile',
    'dsconfig',
    'DTS (Device Tree)',
    'Dust',
    'EBNF',
    'Elixir',
    'Elm',
    'Erlang',
    'Excel',
    'F#',
    'FIX',
    'Fortran',
    'G-Code',
    'Gams',
    'GAUSS',
    'Gherkin',
    'Go',
    'Golo',
    'Gradle',
    'Groovy',
    'HTML, XML',
    'HTTP',
    'Haml',
    'Handlebars',
    'Haskell',
    'Haxe',
    'Hy',
    'Ini',
    'Inform7',
    'IRPF90',
    'JSON',
    'Java',
    'JavaScript',
    'Leaf',
    'Lasso',
    'Less',
    'LDIF',
    'Lisp',
    'LiveCode Server',
    'LiveScript',
    'Lua',
    'Makefile',
    'Markdown',
    'Mathematica',
    'Matlab',
    'Maxima',
    'Maya Embedded Language',
    'Mercury',
    'Mizar',
    'Mojolicious',
    'Monkey',
    'Moonscript',
    'N1QL',
    'NSIS',
    'Nginx',
    'Nimrod',
    'Nix',
    'OCaml',
    'Objective C',
    'OpenGL Shading Language',
    'OpenSCAD',
    'Oracle Rules Language',
    'Oxygene',
    'PF',
    'PHP',
    'Parser3',
    'Perl',
    'Pony',
    'PowerShell',
    'Processing',
    'Prolog',
    'Protocol Buffers',
    'Puppet',
    'Python',
    'Q',
    'QML',
    'R',
    'RenderMan RIB',
    'RenderMan RSL',
    'Roboconf',
    'Ruby',
    'Rust',
    'SCSS',
    'SQL',
    'STEP Part 21',
    'Scala',
    'Scheme',
    'Scilab',
    'Shell',
    'Smali',
    'Smalltalk',
    'Stan',
    'Stata',
    'Stylus',
    'SubUnit',
    'Swift',
    'Test Anything Protocol',
    'Tcl',
    'TeX',
    'Thrift',
    'TP',
    'Twig',
    'TypeScript',
    'VB.Net',
    'VBScript',
    'VHDL',
    'Vala',
    'Verilog',
    'Vim Script',
    'x86 Assembly',
    'XL',
    'XQuery',
    'Zephir'
  ]
