export const SET_AUTH = 'session/SET_AUTH';
export const ADD_NOTIFICATION = 'session/ADD_NOTIFICATION';
export const SET_SIGN_OUT_NOTIFICATION = 'session/SET_SIGN_OUT_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = 'session/CLEAR_NOTIFICATIONS';
export const CLEAR_SIGN_OUT_NOTIFICATION = 'session/CLEAR_SIGN_OUT_NOTIFICATION';
